name:                queens
version:             0.1.0.0
github:              "redraiment/queens"
license:             BSD3
author:              "Zhang, Zepeng"
maintainer:          "redraiment@gmail.com"
copyright:           "Zhang, Zepeng"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            tools

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/redraiment/queens#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative

library:
  source-dirs: src

executables:
  queens-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - queens

tests:
  queens-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - queens
    - hspec
